# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Aliyun
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-4v627lfulndt6g9s.cn-beijing.personal.cr.aliyuncs.com 
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        logout: false
    
    # 安装 Skopeo
    - name: Install Skopeo
      run: |
        sudo apt-get update
        sudo apt-get install -y skopeo

    # 使用 Skopeo 工具同步镜像到 Docker Hub
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        skopeo copy docker://rancher/mirrored-library-registry:2.8.1 docker://crpi-4v627lfulndt6g9s.cn-beijing.personal.cr.aliyuncs.com/fukang/mirrored-library-registry:2.8.1
        skopeo copy docker://rancher/pipeline-jenkins-server:v0.1.4 docker://crpi-4v627lfulndt6g9s.cn-beijing.personal.cr.aliyuncs.com/fukang/pipeline-jenkins-server:v0.1.4
        skopeo copy docker://rancher/mirrored-minio-minio:RELEASE.2020-07-13T18-09-56Z docker://crpi-4v627lfulndt6g9s.cn-beijing.personal.cr.aliyuncs.com/fukang/mirrored-minio-minio:RELEASE.2020-07-13T18-09-56Z

